version: '3.7'

services:
  db:
    image: cassandra:4.1
    container_name: cassandra_db
    ports:
      - "9042:9042"
    volumes:
      - ./db:/var/lib/cassandra
    environment:
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=3utkZEW789dv
      - CASSANDRA_PASSWORD_SEEDER=true
